name: CI run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  install-dependencies:
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: dependencies-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm i

  unit-tests:
    name: Run unit tests and Lint
    runs-on: ubuntu-latest
    needs:
      - install-dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: dependencies-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm test
